### ISSUE TITLE
Question - How to create a Url from template and values?

### ISSUE THREAD

**Issue by brainwipe** [aspnet/Routing#291]
I am building a [hypermedia api](https://github.com/brainwipe/NJsonApi) and I need to create Urls to automatically insert into the output.

Using `IApiDescriptionGroupCollectionProvider`, I can get hold of the `ActionDescriptor` for all the actions for which I need to build URLs for. Each `ActionDescriptor` has a Url template such as:

    articles/{id}

I have the article `id` too. How can I turn this into (for an id of 2):

    articles/2

I tried passing action, controller and values into `UrlHelper.Action` but that produces:

    articles/?id=2

Ideally, I want to do:

```cs
theClassThatSolvesMyProblem.ToUrl(action.ActionDescriptor.AttributeRouteInfo.Template, new { id })
```

[Associated S-O question](http://stackoverflow.com/questions/35729845/how-to-turn-relative-route-into-a-relative-url)

Thank you

**Comment by rynowak** [comment]
`Url.Action` is really the supported mechanism for generating links. You can dig into the infrastructure that backs it is necessary, but just be aware that often those details are subtle to change. See the bottom of this post for details.

If `Url.Action` is behaving as you mentioned, it's likely because you have actions defined like this:
```
[HttpGet("articles")]
public IActionResult Get() { }

[HttpGet("articles/{id}")]
public IActionResult Get(int id) { }
```

We fixed a bug in RC2 for this case where the `articles/{id}` route was not being preferred over `articles` for link generation with inputs like `{ controller = "articles", action = "Get", id = 2 }`. If you're using RC1, and this is what your configuration looks like, here are a few options:

- Rename one of your action methods. Now it's unambiguous which one you want.
- Use a named route - `[Http("articles/{id}", Name = "GetArticleWithId")]` and provide the name to `Url.Action`.
- Use order to explicit configure the order that routes are tried - `[Http("articles/{id}", Order = -1)]`

Any of these should make `Url.Action` do what you want (assuming you have a configuration like the above).

==================

If you still really want to just run the route template directly - the classes here are what's used to implement routing. Here's basically the code you'd need to replicate: https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/Tree/TreeRouter.cs#L400

It sounds like what you're doing is really just going to end up duplicating what `TreeRouter` already does, which is why I'm recommending `Url.Action`. Maybe I'm missing a requirement or two, let me know if there's anything else I can help with.

**Comment by brainwipe** [comment]
Hi Ryan, that answers my question brilliantly.

`Url.Action` is definitely the right way. I am indeed using RC1 and I will update to RC2 immediately (happily there is a good business case to use ASP.NET core!). I am marking the Controller as `[Route("[controller]")]`, and then marking the actions simply with the parameters required `[HttpGet("{id}")]`. The `ApiExplorer` has all the information I need to generate the hypermedia links.

Please consider this question closed and thank you (again) for taking the time to reply (I might build Template-To-Url class based on `TreeRouter` for fun!).

**Comment by rynowak** [comment]
Glad I could help. I'm going to close out this issue, feel free to file more if you have more questions or reopen if you run into problems with this.
