### ISSUE TITLE
Request not matching route with defaults

### ISSUE THREAD

**Issue by kichalla** [aspnet/Routing#324]
A request like `/api/test` is resulting in 404. A request like `/api/test/hello` works fine as expected.

```c#
public class TestController : Controller
{
    [Route("api/test/{seg1=foo}")]
    public string onevariablesegmentwithdefaults(string seg1 = null)
    {
        return $"onevariablesegmentwithdefaults:{seg1}";
    }
}
```

This is working fine with RC2 final packages, so looks like a regression

@rynowak

**Comment by kichalla** [comment]
@javiercn

**Comment by javiercn** [comment]
I'll look at it.

**Comment by javiercn** [comment]
I suspect this might have worked by chance in the previous code. I don't see tests for this, I'm guessing that /{controller=Home}/{action=index} or similar would not have worked in the previous version

**Comment by javiercn** [comment]
I think I found the issue and a potential fix for it. We are not constructing the tree properly, when we have default parameters we don't put the route in the matches list of previous nodes on the tree.
I believe ```if (part.IsParameter && (part.IsOptional || part.IsCatchAll))``` should be ```if (part.IsParameter && (part.IsOptional || part.IsCatchAll || part.DefaultValue != null))``` on https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/Tree/TreeRouteBuilder.cs#L336

I need to look deeper into the issue to make sure all scenarios are covered. I'll add more tests regarding default values, but I'm almost sure that in the previous version of the code it worked because we only tested one default parameter.

/cc @rynowak

**Comment by javiercn** [comment]
Discussed this with @Eilon. Marked for 1.0.1 if you think otherwise voice your concerns @kichalla @rynowak

**Comment by mohsenwolf** [comment]
how can we write somthing like this
[Route("api/test/{number=12:regex(\\d{2})}")]

**Comment by rynowak** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
