### ISSUE TITLE
Using square brackets in regex constraints

### ISSUE THREAD

**Issue by vaindil** [aspnet/Routing#373]
I have a controller that accepts either an ID or a string at a given endpoint. I have the ID function set correctly using `api/departments/{id:long}`, but I cannot figure out how to route to the string endpoint. The `alpha` constraint is not enough as the string can contain numbers.

I'm trying to use this route to accept any valid string but require that the first character be a letter.

```
[Route("api/departments/{deptName:regex(^[a-zA-Z]{1}[a-zA-Z0-9_]*$)}")]
```

This does not work, however:

> For action: 'Namespace.DepartmentsNameController.Get (Namespace)'
Error: While processing template 'api/departments/{deptName:regex(^[a-zA-Z]{1}[a-zA-Z0-9_]*$)}', a replacement value for the token 'a-zA-Z' could not be found. Available tokens: 'action, controller'.

What is the correct way to approach this?

**Comment by dougbu** [comment]
Escape (double) the special characters: `^[[a-zA-Z]]{{1}}[[a-zA-Z0-9_]]*$`. Since matches are not case-sensitive and `{1}` is unnecessary, `^[[a-z]][[a-z0-9_]]*$` works too.

That said, we should improve the message in this case. An un-escaped curly brace leads to an informative message:
```
In a route parameter, '{' and '}' must be escaped with '{{' and '}}'
```
`AttributeRouteModel` currently ignores curly braces when handling square brackets and the
```
An unescaped '[' token is not allowed inside of a replacement token. Use '[[' to escape.
```
message appears only when square brackets appear within square-bracketed tokens.

Nit: The curly-brace message should end with a period 😈

**Comment by vaindil** [comment]
Oh that's awesome. Not sure how I looked at it so many times and didn't see the `{1}` being unnecessary, heh, and I didn't realize even regex matches are not case-sensitive for routing. Thank you so much, especially for helping on a Saturday night!

Would it be helpful to include this in the routing docs? I can open an issue if it would help. I scoured that page to find the info; this issue was my last resort.

**Comment by Eilon** [comment]
Yeah definitely something we can improve.

I think the fixes are:

* [ ] Add a period to the end of the `In a route parameter, '{' and '}'  ...` message
* [ ] For the `While processing template 'foo', a replacement value ...` message, add a blurb about how to escape `[` and `]`. Use something similar (but not identical) to the `An unescaped '[' token` message (because you can't know at this time that it's actually unescaped, so it's just informative, not accusative).

At the same time, I'm working on some improvements to the routing docs to clarify some of this.

**Comment by Eilon** [comment]
Here's my PR to improve the docs if anyone wants to take a look: https://github.com/aspnet/Docs/pull/2450

**Comment by kichalla** [comment]
755d4368400902b44d751e6a8cab5f4587671ca8
