### ISSUE TITLE
TemplateMatcher relies on PathString type as input which limits its functionality to url paths

### ISSUE THREAD

**Issue by ryanfrawley** [aspnet/Routing#398]
I'm using the TemplateMatcher to build tenant/subdomain functionality in my 1.1 core project. Due to the TemplateMatcher function TryMatch relying on a PathString instead of a regular String as input, I can only use relative paths beginning with a "/". My actual input is "test.example.com". Because it does not begin with a slash, I get an exception when TemplateMatcher tries to instantiate the input as a PathString. 

Example:
`ParsedTemplate = TemplateParser.Parse("{tenant}.example.com");`
`_matcher = new TemplateMatcher(ParsedTemplate, Defaults);`

`_matcher.TryMatch("test.example.com", values);`
previous line throws an exception because the first parameter needs to start with a slash.

I feel that requiring a PathString here is an oversight that artificially limits what can be done with Template Routes. There should be support for doing non-url templates.

**Comment by Eilon** [comment]
I believe that TemplateMatcher (and, in fact, all of Routing's built-in parsing stuff) is specifically about working with the "path" portion of the URL. It is not designed to work with any other part of the URL (scheme, port, host, query string, etc.). For this reason it needs to use many URL-path-specific APIs, because rules for various parts of the URL are quite different with regard to what is valid, how to encode/decode, etc.
