### ISSUE TITLE
Int parameter constraint is greedily splitting

### ISSUE THREAD

**Issue by aalcutt** [aspnet/Routing#412]
Brought up in this [stackoverflow post](https://stackoverflow.com/questions/40009935/asp-net-core-route-attributes-id-and-hyphenated-slug-separated-by-a-hyphen) Not my stackoverflow post but it was the same issue I encountered and there is no good way to work around this.

Trying to use a route that is like /item/{id:int}-{name} doesn't work when name has hyphens because it will split the id parameter before checking for an integer, and match on the last hyphen instead of the first.

**Comment by Eilon** [comment]
Unfortunately this is just not supported in routing. It's recommended to use the `/` character to separate these data values because splitting on `/` is the first thing that happens and the only reliable way to parse this data. An alternative is to capture the entire segment as a single field, e.g. `item/{complexdata}` and then later parse `complexData` however you want.
