### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#439]
We should add logging to:
- [ ] DispatcherMiddleware
- [ ] EndpointMiddleware
- [ ] DispatcherBase + all subclasses
- [ ] EndpointSelector + all subclasses

Take a stab at this and try to figure out the ideal things to log - use routing as an inspiration.

**Comment by anurse** [comment]
One the one, as referenced in various issues (https://github.com/aspnet/SignalR/issues/876 https://github.com/aspnet/Hosting/issues/1205 https://github.com/aspnet/Mvc/issues/6818): make sure that when you specify an Event ID, you use `new EventId([number], "[name]")` rather than just an `int`. Having names associated with the events makes it much easier to filter and avoids having to look up obscure `int`s. The names should be unique but only within a particular `ILogger` category.

**Comment by anurse** [comment]
That and: Log lots, use Trace if you're worried about logging too much :).

**Comment by jbagga** [comment]
@rynowak Should the `EndpointSelectorContext` have a logger? Then `HttpMethodEndpointSelector` can use context.Logger inside the `SelectAsync` [method](https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Dispatcher/HttpMethodEndpointSelector.cs#L12). Is it correct to get that from DI [here](https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Dispatcher/EndpointSelectorContext.cs#L16)?

**Comment by rynowak** [comment]
> Should the EndpointSelectorContext have a logger? 

No, we don't usually pass services this way. Let's discuss this at the meeting tomorrw
