### ISSUE TITLE
Move Routing build for Windows from AppVeyor to Jenkins

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#524]
Routing is currently using AppVeyor. Lets:

- [ ] Enable build on Jenkins
- [ ] Disable AppVeyor

As far as I know routing uses nothing beyond .NET on build.

**Comment by JamesNK** [comment]
Apparently VSTS build is the new hotness and it is close to being ready. This is not at all urgent so will wait to see where buildworld goes.

**Comment by rynowak** [comment]
OK cool. I know @ryanbrandenburg has been looking into that. @ryanbrandenburg if you need a guinea pig, you can use us!

**Comment by ryanbrandenburg** [comment]
I've got a couple repos that are being done first because they're likely to work out the kinks in our setup, but it'll be on the way soon. One thing though is that at least for now we'll only be running PR checks for PR's originating from the main fork, so external contributors wouldn't get anything if we turn off AppVeyor.

**Comment by Eilon** [comment]
VSTS for everything. We probably don't need anything specific in this repo, though, because we'll be updating the builds in *all* the repos over the coming weeks/months.

**Comment by JamesNK** [comment]
ok! Nothing to do here then
