### ISSUE TITLE
MVC Integration - IUrlHelper implementation

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#530]
## Requirements
- Works with both conventional and attribute routing
- Can generate links based on 'route name'
- Can generate links just based on route values.
- Attribute routing's link generation should match what conventional routing is doing

**Comment by JamesNK** [comment]
@rynowak So MVC provides a data source for endpoints, and MVC also needs to consume the data source for generating URLs. I'm guessing when generating URLs that should MVC care about more than just its own data source?

**Comment by kichalla** [comment]
> I'm guessing when generating URLs that should MVC care about more than just its own data source?

Could you elaborate more on that? Not clear on what you meant here.

At this point I am thinking of the following about this: You can @rynowak can correct me if I am missing something:
**Scenario**:  We should be able to generate links outside the context of a request
My thoughts:
In general, we should be able to go through a route table and find a matching route which satisfies the segments (and constraints) based on the given values.
There could be named or unnamed segments. This particular part doesn't need to be part of the current request IF we consider just generating a non-absolute url. 
I tried a prototype of this which is straightforward but I am sure its missing some features.
Let's call this new url helper 'UrlGenerator' for easy reference. This UrlGenerator can be registered as a singleton.

MVC's [UrlHelper ](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/IUrlHelper.cs)can internally use this new UrlGenerator and generate MVC specific stuff.

Regarding 
> So MVC provides a data source for endpoints, and MVC also needs to consume the data source for generating URLs

UrlGenerator can inject DispatcherOptions to retrieve the endpoints from the datasources.

**Comment by JamesNK** [comment]
> Could you elaborate more on that? Not clear on what you meant here.

Endpoints are generated from MVC route constraints. In the same app endpoints can also be defined outside MVC, either manually or other frameworks supplying a data source.

I'm guessing that when we generate URLs inside MVC the URLs should consider all data sources, not just MVCs.

**Comment by rynowak** [comment]
> So MVC provides a data source for endpoints, and MVC also needs to consume the data source for generating URLs.

Yes I agree. 

One thing that I think it central to the value proposition is that we want to separate the lookup of the addresses, from the processing of the templates. I think a good URL generation system will be two-phase.

I think what exactly I mean by this will become a little more clear.

-----

In general the existing code operates at two different layers, and also in two ways (just providing background).

MVC's URL helper (when calling `Url.Action`) **copies** the route values for controller and action (and page) from the **ambient values** to the **values** https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Routing/UrlHelper.cs#L70

This will become important later.

-----

In conventional routing - MVC provides the **ambient values** and the **values** to the routing system, which processes the set of routes in order. Each route is given an opportunity to generate a URL, and the first one that wins succeeds.

In general this works because each MVC route expects the action, controller, and possibly area route values to be present. (recall that UrlHelper makes that happen).

For example linking to a page, would **not** satisfy the requirements to generate a URL with a conventional route because you would **not** call `Url.Action` and would not end up with the controller and action route values.

--

In attribute routing - MVC provides the **ambient values** and the **values** to the routing system, which processes a big lookup table to try and find the action. This is similar to how action selection works. 

In general this works because we build this lookup table with the assumption that route values and actions are associated in some orderly way. For instance, all controller actions have an action and controller route value, and possibly area, but they all **also** don't include a route value for *page*. 

This means that things we can generate links to are put into distinct sets, and this makes it easier to determine which set of things that we're selecting from. I call this idea **key spaces** and I think it's a helpful concept - it largely works to keep controllers and pages separate.

-----

For things aren't controllers or pages, consider the idea that an **address** might be looked up with a set of route values... or it might be looked up with a route name.... or it might be looked up with a MethodInfo. 

I don't take as a given that a system including all kinds of things would *want* the same kind of complexity that MVC's system has. One idea that might work *really* well would be allow someone to associate a string identifier with an address. It's really simple and well understood, very little can go wrong.

**Comment by kichalla** [comment]
Thanks for the write up!, @rynowak. I am digesting this information now and will let you know if I have any questions.

**Comment by rynowak** [comment]
# SO

So, I slept on this discussion, and I concerned that we're getting ahead of ourselves. Do think it would be productive to use the top post, to track what the requirements are in this area. I'm worried that @JamesNK and @kichalla are still missing some context on what we're building in this area. It wouldn't be fun or fair to send you off to invent something without discussion what problems we need to solve first. 

Does that make sense? @kichalla would you up be up for putting together an initial short list of what you think the requirements are around URL generation so we can continue the discussion?

PS. this isn't the info dump I promised you yesterday. I'm still working on that.

**Comment by kichalla** [comment]
> Does that make sense? @kichalla would you up be up for putting together an initial short list of what you think the requirements are around URL generation so we can continue the discussion?

Sure @rynowak I am working on that actually. I will share the requirements in this thread asap.

**Comment by rynowak** [comment]
Related to this, here's the brain dump I promised on route value invalidation: https://gist.github.com/rynowak/174c46b31f52d9674b55bf27dbf8b19d

**Comment by kichalla** [comment]
https://github.com/aspnet/Mvc/commit/a0a9c2c58555264491860f06d4e75e215d821738
