### ISSUE TITLE
Allow for route initialization before the first request

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#550]
Tracking https://github.com/aspnet/Mvc/issues/6867

**Comment by rynowak** [comment]
Closing is as done because it turns out I thought about this a very long time ago. https://github.com/aspnet/Routing/blob/release/2.2/src/Microsoft.AspNetCore.Routing/EndpointRoutingMiddleware.cs#L85

This is better than adding an option IMO because this addresses the underlying problem (blocking initialization).
