### ISSUE TITLE
Support 'defaults' with [action] syntax for attribute routes

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#557]
Tracking https://github.com/aspnet/Mvc/issues/3286

**Comment by rynowak** [comment]
If we wanted to do this. We would do it by allowing attribute routes to specify tokens/parameters with the same syntax that is allowed for conventional routes. We basically have the infrastructure to do this already since it do it with Endpoint Routing for conventional routes.

We've had a few asks for this but it doesn't seem high priority, so moving to backlog.

**Comment by JamesNK** [comment]
So with this fix - https://github.com/aspnet/Mvc/pull/8447 - we now support normal parameters in route attributes which can have defaults, e.g. `[Route("{controller=Home}/{action=Index}")]`.

I think we can close this // @rynowak

**Comment by rynowak** [comment]
Lovely. Let's close this then.
